# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20160512_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
