# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20160512_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cover_url',
            field=models.URLField(null=True),
        ),
    ]
