# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_cover_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
