# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20160517_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='playing',
            field=models.BooleanField(default=False),
        ),
    ]
