# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('user', 'video')]),
        ),
    ]
